"""Genblaze storage sinks bound to the Spatialize B2 configuration."""

from genblaze_core import KeyStrategy, ObjectStorageSink

from ..config import Settings


def build_genblaze_sink(settings: Settings) -> ObjectStorageSink | None:
    """A B2-backed genblaze sink, or None when running on local storage.

    In local mode pipelines run sink-less; generated bytes are persisted
    through the existing ObjectStore by the calling service instead.
    """
    if settings.storage_backend != "b2":
        return None
    from genblaze_s3 import S3StorageBackend

    backend = S3StorageBackend.for_backblaze(
        settings.b2_bucket,
        region=settings.b2_region,
        key_id=settings.b2_key_id,
        app_key=settings.b2_app_key,
    )
    return ObjectStorageSink(
        backend,
        prefix="generated",
        key_strategy=KeyStrategy.HIERARCHICAL,
    )
