"""Genblaze storage sinks bound to the Spatialize B2 configuration."""

import logging

from genblaze_core import KeyStrategy, ObjectStorageSink

from ..config import Settings

logger = logging.getLogger(__name__)


def build_genblaze_sink(settings: Settings) -> ObjectStorageSink | None:
    """A B2-backed genblaze sink, or None when running on local storage.

    In local mode pipelines run sink-less; generated bytes are persisted
    through the existing ObjectStore by the calling service instead. A
    misconfigured bucket degrades to sink-less rather than failing boot.
    """
    if settings.storage_backend != "b2":
        return None
    from genblaze_s3 import S3StorageBackend

    try:
        backend = S3StorageBackend.for_backblaze(
            settings.b2_bucket,
            region=settings.b2_region,
            key_id=settings.b2_key_id,
            app_key=settings.b2_app_key,
        )
    except Exception as error:
        logger.warning("Genblaze B2 sink unavailable, running sink-less: %s", error)
        return None
    return ObjectStorageSink(
        backend,
        prefix="generated",
        key_strategy=KeyStrategy.HIERARCHICAL,
    )
